baseURL = 'https://Pacqu-ER.github.io/appunti-scuola/'
languageCode = 'it-it'
title = "Appunti HTML, CSS e JavaScript"
theme = 'hextra'

#hugo server -D per startare#
#git add .#
#git commit -m "prova3"#
#git push#
#https://github.com/Pacqu-ER/appunti-scuola per andare su github#
# Attiva la ricerca integrata
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu in alto (Header)
[[menu.main]]
  name = "Appunti"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "Informazioni"
  pageRef = "/about"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true